### ISSUE TITLE
Broken folder names breaks git pull

### ISSUE THREAD

**Issue by AmyMoriyama** [t-affeldt/climate#4]
As the title says. Screenshot attached. When doing a git pull of this repo, all the folders are empty.

![climate](https://user-images.githubusercontent.com/87048190/124835082-c2963880-df4e-11eb-8f3b-66bf36f3723a.png)

**Comment by t-affeldt** [comment]
Check the readme for cloning instructions. You need to add the ``--recursive`` flag in order to download sub-repositories.
