### ISSUE TITLE
crashes in mineclone 2

### ISSUE THREAD

**Issue by Ranko-Saotome** [t-affeldt/climate#5]
ModError: Failed to load and run script from /home/owner/Applications/minetest-5.6.1/bin/../games/mineclone2/mods/ITEMS/mcl_lightning_rods/init.lua:
.../games/mineclone2/mods/ITEMS/mcl_lightning_rods/init.lua:115: attempt to call field 'register_on_strike' (a nil value)
stack traceback:
	.../games/mineclone2/mods/ITEMS/mcl_lightning_rods/init.lua:115: in main chunk
Check debug.txt for details.

**Comment by t-affeldt** [comment]
Sorry for this late reply. According to your crash log, this issue arises in a mod called mcl_lightning_rods, not one of my mods.
