### ISSUE TITLE
Lack of color saturation when running on 5.7.0

### ISSUE THREAD

**Issue by pquesinb** [t-affeldt/climate#7]
After updating the server to 5.7.0 (from 5.6.1), the colors are severely washed out, almost black & white, when regional_weather is enabled. Disabling it returns colors to normal. Also, if you are below -100m, the color returns to normal so I guess it's related to fog or other atmospheric effects being disabled underground.

**Comment by pquesinb** [comment]
Looks like that color-saturation calculation is done here, in line 40 of ../ca_weathers/ambient.lua:
local light_saturation = map_range(cloud_shadows + daytime_shadows, 0.9, 1.1)

I made the following change to line 53 to just plug a value of 1 in there as a temporary fix, but it of course messes up the cool weather-related lighting/saturation effects:

root@racknerd-xxxxxx:/var/games/minetest-server/.minetest/mods/climate/regional_weather/ca_weathers# diff ambient.lua.org ambient.lua

`53c53`
`<` 		saturation = light_saturation
`---`
`>` 		saturation = 1

**Comment by AyeGeeToo** [comment]
Just installed the mod in 5.8.0 and am getting the same issue. The game runs ok for a few seconds before the colours wash out.

Have used the temporary fix by @pquesinb so I can play with the mod active. Thank you for that.

> `53c53` `<` saturation = light_saturation `---` `>` saturation = 1

PS I am enjoying the weather features, great job.

**Comment by jgordon510** [comment]
This appears to fix it.  On line 17 in map_range, change the return to this:
return val*(high-low)+low

(I think the algebra is just wrong for the map function.)

**Comment by t-affeldt** [comment]
This should be fixed in the newest version. :)
